### ISSUE TITLE
Getting demo working

### ISSUE THREAD

**Issue by kcleal** [pongasoft/emscripten-glfw#1]
Hi @ypujante,

Thanks for this library port, it looks great. However, I am new to wasm and emscripten and am having trouble getting the demo or examples working. Would you be kind enough to help me get started? I have cloned the repo, activated the emsdk environment and tried building the demo using:
```
em++ --use-port=contrib.glfw3:disableWarning=true:disableMultiWindow=true src/main.cpp src/Triangle.cpp -o hello.html
```

However, when I click on the html files I only see a black box, or if I try using `python3 -m http.server -d hello.html` then I get a 404 error message on firefox. I'm probably missing something obvious, but how do I get the example working on my local machine? Thanks

![image](https://github.com/pongasoft/emscripten-glfw/assets/42997789/376c9c4d-2391-4c7b-a645-bb64719703e9)

**Comment by ypujante** [comment]
You cannot open the file with a `file://` protocol due to javascript cross scripting restrictions. You have to start the python server like this:

```
python3 -m http.server -d <WWW_DIR> <PORT>
``` 

* -d needs to be a directory NOT a file like in your comment
* then you need to navigate to http://localhost:<PORT>/hello.html
