### ISSUE TITLE
Raylib support, missing glfwSetWindowIconifyCallback , glfwSetDropCallback, glfwSwapBuffers 

### ISSUE THREAD

**Issue by Rucadi** [pongasoft/emscripten-glfw#10]
When trying to use this GLFW for making a fullscreen app on raylib, I get these warnings which are not present in the emscripten js library.

WARNING: GLFW: Error: 0 Description: [Warning] glfwSetWindowIconifyCallback is not implemented on this platform
WARNING: GLFW: Error: 0 Description: [Warning] glfwSetDropCallback is not implemented on this platform
WARNING: GLFW: Error: 0 Description: [Warning] glfwSwapBuffers is not implemented on this platform

This missing functionality seems to be crucial to get raylib to fullscreen, breaking the rendering after trying the setup the full screen.

I don't know if you could point to how difficult is for these features to be supported and if you could point me in the right direction to maybe implement them

**Comment by ypujante** [comment]
These warnings have absolutely nothing to do with fullscreen support. I am not sure why you are saying this is a crucial functionality for fullscreen.

Raylib has a PLATFORM_WEB implementation, which uses the Emscripten built-in GLFW port which does this:

* `glfwSwapBuffers` => does nothing (does not issue a warning)
* `glfwSetWindowIconifyCallback` => stores the callback without ever calling it
* ` glfwSetDropCallback` => is implemented BUT is dealing with drag and drop **NOT** fullscreen

More importantly none of these have anything to do with fullscreen. The warning messages are just telling you that they are no op with this implementation.

Why are you trying to use this port since Raylib already supports PLATFORM_WEB?

**Comment by Rucadi** [comment]
Hello, thanks for your answer!

Probably I'm confused on how this works, I was compiling with -sUSE_GFLW and also your contrib port and linking the release raylib at the same time. 

This worked for USE_GLFW but when I tried with your port, I found out that when trying to get into full-screen the rendering stopped working and the logs had those errors.

Raylib in their documentation: https://github-wiki-see.page/m/raysan5/raylib/wiki/Working-for-Web-(HTML5)

states that we should use the emscripten flag -s USE_GLFW=3  in order to compile, which is why I'm replacing it with your contrib just to test if the features provided suits better.  

So for me it seems like raylib requires to link against GLFW and that's why I'm linking it.

**Comment by ypujante** [comment]
Yes Raylib requires an implementation of GLFW. 

If Raylib is not working with this implementation of GLFW, it is most likely an issue with Raylib.

**Comment by Rucadi** [comment]
Ok!  Thank you for your time, I'll fallback to the default implementation that seems to work with this version of raylib.

I'll leave here the full log that I received for if it serves to someone in the future.

```

INFO: Initializing raylib 5.5
INFO: Platform backend: WEB (HTML5)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 0 Description: [Warning] Hint 131077 not currently supported on this platform.
WARNING: GLFW: Error: 0 Description: [Warning] Hint 131079 not currently supported on this platform.
WARNING: GLFW: Error: 0 Description: [Warning] Hint 139266 not currently supported on this platform.
WARNING: GLFW: Error: 0 Description: [Warning] Hint 139267 not currently supported on this platform.
WARNING: GLFW: Error: 0 Description: [Warning] Hint 139275 not currently supported on this platform.
WARNING: GLFW: Error: 0 Description: [Warning] glfwSetWindowIconifyCallback is not implemented on this platform

WARNING: GLFW: Error: 0 Description: [Warning] glfwSetDropCallback is not implemented on this platform

INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GL: Supported extensions count: 67
INFO: GL: OpenGL device information:
INFO:     > Vendor:   WebKit
INFO:     > Renderer: WebKit WebGL
INFO:     > Version:  OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium))
INFO:     > GLSL:     OpenGL ES GLSL ES 1.00 (WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium))
INFO: GL: VAO extension detected, VAO functions loaded successfully
WARNING: GL: NPOT textures extension not found, limited NPOT support (no-mipmaps, no-repeat)
INFO: GL: DXT compressed textures supported
INFO: PLATFORM: WEB: Initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 2] Default texture loaded successfully
INFO: SHADER: [ID 3] Vertex shader compiled successfully
INFO: SHADER: [ID 4] Fragment shader compiled successfully
INFO: SHADER: [ID 5] Program shader loaded successfully
INFO: SHADER: [ID 5] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 12] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: SYSTEM: Working Directory: /
INFO: TIMER: Target time per frame: 16.667 milliseconds
WARNING: GLFW: Error: 0 Description: [Warning] glfwSwapBuffers is not implemented on this platform

WARNING: GLFW: Error: 0 Description: [Warning] Out of order pointerLock request
```

**Comment by ypujante** [comment]
@Rucadi I know that GLFW does not support 4k and since my implementation defaults to 4k, I am wondering if that could be an issue. You could try to disable 4k/Hi DPI entirely and see if that works:

https://github.com/pongasoft/emscripten-glfw/blob/master/docs/Usage.md#hi-dpi-support

I am not saying it is the issue, but just an idea...
