### ISSUE TITLE
glfwGetKey must return one of `GLFW_PRESS` or `GLFW_RELEASE`

### ISSUE THREAD

**Issue by les-sosna** [pongasoft/emscripten-glfw#3]
repro steps:
- run live demo
- watch `glfwGetKey`
- press and hold `A`
- observed behavior: `A` key state changes from `R` to `P` and shortly after it changes to `H`

expected: `glfwGetKey` reported `A` key should remain in `P` state while the key is held per `glfwGetKey` spec

**Comment by ypujante** [comment]
Thank you for reporting. I can see what you are talking about and it is indeed specified this way as can be seen in GLFW/glfw3.h:

```
// for glfwGetKey
 *  This function returns the last state reported for the specified key to the
 *  specified window.  The returned state is one of `GLFW_PRESS` or
 *  `GLFW_RELEASE`.  The action `GLFW_REPEAT` is only reported to the key callback.
```

I will fix the issue

**Comment by ypujante** [comment]
@les-sosna The issue has been fixed and the code pushed. The demo has been updated as well (you might have to refresh until the version is 3.4.0.20240617-nw at the bottom right of the screen.

Note that I also did a [PR](https://github.com/emscripten-core/emscripten/pull/22103) in emscripten but I do not have any control of when this PR will be merged and which version of emscripten it will be available in (hopefully the next one). But this could take a few days to a few weeks.

If you need the bug fixed right away, you can use the port file under  `port` like this: `--use-port=port/emscripten-glfw3.py`
