### ISSUE TITLE
How this example can get cursor pos and mouse event outside of canvas?

### ISSUE THREAD

**Issue by uysalibov** [pongasoft/emscripten-glfw#7]
When i press mouse click in canvas and then release outside of canvas. My glfw mouse callback cannot access release event.

**Comment by ypujante** [comment]
Can you try with the live [demo](https://pongasoft.github.io/emscripten-glfw/test/demo/main.html)?

I just tried and I don't see the issue that you are talking about: I click on the canvas on the left (grey background), I then move the mouse outside the canvas and release: the `glfwSetMouseButtonCallback` line reports that the mouse button is released.

<img width="421" alt="Screenshot 2024-08-25 at 05 46 46" src="https://github.com/user-attachments/assets/861e4e35-865e-403d-8e3c-4a0a900f54e3">

The code of this demo is [here](https://github.com/pongasoft/emscripten-glfw/blob/47da6a65848e4626f414d5c5ff952200e3d65a22/test/demo/src/Triangle.cpp#L389):

```cpp
void onMouseButtonChange(GLFWwindow* window, int button, int action, int mods)
{
  setHtmlValue(window, "glfwSetMouseButtonCallback", "%d:%s:%d", button, actionToString(action), mods);
  reinterpret_cast<Triangle *>(glfwGetWindowUserPointer(window))->onMouseChange(button, action, mods);
}
```

**Comment by ypujante** [comment]
@uysalibov did you get the chance to test the demo? Are you experiencing the issue with the demo?

**Comment by ypujante** [comment]
Cannot reproduce / no follow up from user
