### ISSUE TITLE
PROXY_TO_PTHREAD support

### ISSUE THREAD

**Issue by ieremius** [pongasoft/emscripten-glfw#9]
I'm porting a large Windows GLFW/OpenGL app to WASM.

I've hoped to do it without major modifcations to our main/rendering thread. So I'm using -pthread, PROXY_TO_PTHREAD, and OFFSCREENCANVASES_TO_PTHREAD flags.

(I saw your Asyncify example, but it looks like pthreads is the better alternative for us.)

Naively changing one of your demos to build with those options, I get "window undefined" in _emscripten_glfw3_context_init(), of course.

I tried calling a couple of your JS methods from C++ with MAIN_THREAD_EM_ASM, and then they worked great.

I also noticed Emscripten has things like this in the .js file, which seems like another way to go:
```
  function _emscripten_set_focus_callback_on_thread(target, userData, useCapture, callbackfunc, targetThread) {
  if (ENVIRONMENT_IS_PTHREAD)
    return proxyToMainThread(11, 0, 1, target, userData, useCapture, callbackfunc, targetThread);
  return registerFocusEventCallback(target, userData, useCapture, callbackfunc, 13, "focus", targetThread)
  }
```
So I'm wondering, before I get to deep into this:
- Do you think I could get contrib.glfw to work using one of the two above methods with all the JS calls? Or do you think I will hit up against some intractable issue?
- Or is there some easier way to go about it?

Thanks!

**Comment by ypujante** [comment]
To be honest I am not at all familiar with the options you are using. But I would certainly be willing to look into it if it can improve this project to work in other scenario.

Could you provide a bit of background of why you are using these options and what do they do exactly? That would help me bootstrap investigating this.

Thanks

**Comment by ieremius** [comment]
Thanks for the response. Sure I can provide some background....

-pthread: enables threading support in the C++. So you can create threads for parallel processing. This requires SharedArrayBuffer and so one needs to follow [Making your website "cross-origin isolated" using COOP and COEP](https://web.dev/articles/coop-coep). (Running a local http server with Emscripten emrun takes care of this for us.) The device running the browser also needs to have more than one logical core, of course.

-sPROXY_TO_PTHREAD: Causes C++ main() to get called from a pthread - not the main browser thread - so you can do synchronous operations in the thread executing your main(), without causing problems for the main browser thread. Like in your example_asyncify README where you say, "Allows the code to be written like you
would for a normal desktop application." So it's the same goal, done a different way. [More info](https://emscripten.org/docs/tools_reference/settings_reference.html#proxy-to-pthread)

-sOFFSCREENCANVAS_SUPPORT: "enables support for transferring canvases to pthreads and creating WebGL contexts in them." [More info](https://emscripten.org/docs/tools_reference/settings_reference.html#offscreencanvas-support)

-sOFFSCREENCANVASES_TO_PTHREAD': specify "canvases to proxy over to the pthread at program startup" [More info](support)https://emscripten.org/docs/tools_reference/settings_reference.html#offscreencanvases-to-pthread)

My command line:
emcc --use-port=emscripten-glfw3.py --shell-file=shell.html -sPROXY_TO_PTHREAD
 -pthread -g -sOFFSCREENCANVAS_SUPPORT -sOFFSCREENCANVASES_TO_PTHREAD='canvas' main.cpp -o build/index.html

I happen to be using the example_resizable_container_with_handle demo.

Note that I am using a local copy of emscripten-glfw3.py because it needs the -pthread flag also.

-g: I'm generating debug info and debugging using the Chrome DWARF plugin.

I can step into _emscripten_glfw3_context_init() and see that window is undefined, which makes total sense because the function is executing in the pthread and not the main browser thread.

MAIN_THREAD_EM_ASM: Emscripten macro that allows you to execute JavaScript code on the main browser thread from within your C/C++ code.

I modified Context.cpp to use that macro as an experiment:

```
Context::Context()
{
  fScale = static_cast<float>(emscripten_get_device_pixel_ratio());

  MAIN_THREAD_EM_ASM({
  _emscripten_glfw3_context_init($0, $1, $2, $3, $4, $5, $6, $7);
  }, this,
                                fScale,
                                ContextScaleChangeCallback,
                                ContextWindowResizeCallback,
                                ContextKeyboardCallback,
                                ContextClipboardStringCallback,
                                emscripten_glfw_request_fullscreen,
                                ContextErrorHandler
                                );
```

After that change,  _emscripten_glfw3_context_init() does have access to the window object when it executes, and initialization succeeds.

I also tried calling a second function this way to check that the GLFW object was intact from initialization, and it was.

So, that all seems promissing. But I'm new to most of this.

Thanks again.

**Comment by ypujante** [comment]
Thanks for providing details on the various options as well as what you tried. I think that gives me a good starting point.

I am new to all of this too as I have never experimented with pthread in Emscripten. 

I need to spend some time investigating these concepts and how I would change this library to integrate them in a manner that would not impact the current way of doing things. I also need to understand how GLFW, in a multi thread environment, works.

I can't commit to a timeline since I am busy with other tasks at the moment and I have no clue how long it will take me to get a grasp of all this. But I am definitely interested in investigating further.

**Comment by ypujante** [comment]
I looked at the Emscripten documentation, and in the [Proxying](https://emscripten.org/docs/porting/pthreads.html#proxying) section it talks about this:

> The Web allows certain operations to only happen from the main browser thread, like interacting with the DOM. As a result, various operations are proxied to the main browser thread if they are called on a background thread. See [bug 3495](https://github.com/emscripten-core/emscripten/issues/3495) for more information and how to try to work around this until then. To check which operations are proxied, you can look for the function’s implementation in the JS library (src/library_*) and see if it is annotated with __proxy: 'sync' or __proxy: 'async'; however, note that the browser itself proxies certain things (like some GL operations), so there is no general way to be safe here (aside from not blocking on the main browser thread).

And then I noticed in your attempt at modifying `Context.cpp` you modified how you call `emscripten_glfw3_context_init` (which is MY code) but **not** how you call `emscripten_get_device_pixel_ratio` which is Emscripten code...

And this code is defined this way:

```js
  emscripten_get_device_pixel_ratio__proxy: 'sync',
  emscripten_get_device_pixel_ratio: () => {
#if ENVIRONMENT_MAY_BE_NODE || ENVIRONMENT_MAY_BE_SHELL
    return (typeof devicePixelRatio == 'number' && devicePixelRatio) || 1.0;
#else // otherwise, on the web and in workers, things are simpler
#if MIN_FIREFOX_VERSION < 18 || MIN_CHROME_VERSION < 4 || MIN_SAFARI_VERSION < 30100 // https://caniuse.com/#feat=devicepixelratio
    return window.devicePixelRatio || 1.0;
#else
    return devicePixelRatio;
#endif
#endif
  }
```

I think the BIG difference is the `emscripten_get_device_pixel_ratio__proxy: 'sync',` line...

So I feel like if you changed the file `lib_emscripten_glfw3.js` to add

```js
  emscripten_glfw3_context_init__proxy: 'sync',
``` 

it should just work WITHOUT having to change the C++ code at all.

Of course this change needs to be done for all js methods, but that is kind of trivial.

If that works, then I feel like implementing pthread support would be:

1) add a new option to `emscripten-glfw3.py` to compile with the `-pthread` flag
2) modify `lib_emscripten_glfw3.js` to add the proxy/sync line for every js method
3) add a new example (`example_pthread`) to demonstrate/test the feature

**Comment by ieremius** [comment]
That's a great observation and suggestion. I noticed their functions got generated like this (where 4 in this case is an index into the table):

```
function _emscripten_get_device_pixel_ratio() {
  if (ENVIRONMENT_IS_PTHREAD)
    return proxyToMainThread(4, 0, 1);
  
      return (typeof devicePixelRatio == 'number' && devicePixelRatio) || 1.0;
    
  }

var proxiedFunctionTable = [
  _proc_exit,
  exitOnMainThread,
  pthreadCreateProxied,
  setCanvasElementSizeMainThread,
  _emscripten_get_device_pixel_ratio, 
...
```
...but I had wondered how to get functions included in that scheme. I'll try 'sync' tomorrow and let you know how it goes.

Thanks!

**Comment by ypujante** [comment]
I don't know if you got the change to try it.

That being said, I was able to change the code and write a test/example (example_pthread) which demonstrates that pthread is now working:

```cpp
 * The purpose of this example is to demonstrate how to use pthread.
 * It creates 2 threads that are incrementing a counter to simulate work on separate threads.
 * In total there are 4 threads:
 * - the main browser thread which executes `jsRenderFrame` and the key callback (`onKeyChange`)
 * - the `main` function which is its separate thread due to `-sPROXY_TO_PTHREAD` option
 * - two worker threads (the counters) started in `main`
```

I am going to close this issue since it is implemented and will make a PR into Emscripten to deploy it as a contrib port (which might take some time...)

If you have any issue, you can reopen it or open a new one.

**Comment by ieremius** [comment]
Hi @ypujante, thanks, I'll check this out.
This week I did start by adding those 'sync' lines. Then it got more complicated with offscreen canvases which it seemed I needed for WebGL in a pthread. I'll try your update tomorrow and see how it works in my case.
My situation is tested by Emcripten test_webgl_offscreen_canvas_in_proxied_pthread() (Except I removed -sASYNCIFY from that test and fixed it by using emscripten_set_main_loop_arg()).
I'll invite you to the cloned repo so you can see what I was doing.

**Comment by ypujante** [comment]
Let me know how it goes. You can check the example I created to test pthread (example_pthread) and start from there.

You can see that I am accessing the canvas from the main thread.

**Comment by ypujante** [comment]
I think that the changes I have made to support pthread should be enough for this library:

* enable the `-pthread` flag in the port file
* decorate every single js call with the __proxy: 'sync' syntax

The test that I added seems to demonstrate that it works: the main thread, which is calling into the library, is not even running in the browser main thread. The only time when I force the call on the main browser thread is when I access the canvas. I believe if you want to access the canvas in another thread (using offscreen canvas) you should be able to do that with the proper set of flags, but I am not sure how that would affect this library.

One thing to keep in mind, is that like the desktop implementation of GLFW, this implementation is NOT thread safe. So you should not call into it from various threads at the same time.

Of course if I missed anything or if there is anything else I need to do to support this, I will be more than happy to add it.

**Comment by ieremius** [comment]
@ypujante thanks, I tried it - I'll elaborate on the additional thing as a separate issue.
